### ISSUE TITLE
Atomicity of State Balance

### ISSUE THREAD

**Issue by stoqnkpL** [LimeChain/hedera-services#853]
Refactor to improve atomicity of state balance changes and record transfer list construction
https://github.com/hashgraph/hedera-services/issues/2864

- [ ] Go through Michael's description and research current implementation

- [ ] Log separate issues as part of #2864 (or create a checklist) to help involve more people 

- [ ] Log issues for other record change types (other than balance changes)
